---
- hosts: localhost
  become: true
  vars:
    container_count: 1
    default_container_name: nginx-webserver
    default_container_image: nginx:1.23.1-alpine
  roles:
    - docker
    - nginx
    - logrotate
  
