version: '3'

services:
  api:
    ports:
      - 8000:8000
    build:
      context: ./node
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - backend-tier

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    networks:
      - backend-tier    
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend-tier
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  db:
    driver: local
  nginx:
    driver: local
networks:
  backend-tier:
    driver: bridge      
