version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    networks:
      - backend-tier    
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/ssl/
  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend-tier
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  backend: 
    image: application-image
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - backend-tier

volumes:
  db:
    driver: local
networks:
  backend-tier:
    driver: bridge      
