---
# tasks file for logrotate
- name: "Create logrotate config file"
  file:
    path: "/etc/logrotate.d/nginx"
    state: touch
    mode: "0644"

- name: "Add config block to logrotate config file"
  blockinfile:
    path: "/etc/logrotate.d/nginx"
    block: |
      /var/log/nginx/*.log {
        maxsize 100M
        copytruncate
        notifempty
        missingok
        compress
        delaycompress
      }
